#=========================================================================
# Travis CI Configuration
#=========================================================================
# This file configures Travis CI to automatically run tests for this RTL
# project everytime a commit is made.

language: cpp

# Prefer use of container-based environment as they start up faster and
# provide more RAM and CPU cores.
sudo: false

# Install the build requirements
addons:
  apt:
   sources:
    # For gcc-4.8
    - ubuntu-toolchain-r-test
   packages:
    # Dependencies from tutorial
    - autoconf
    - automake
    - autotools-dev
    - curl
    - libmpc-dev
    - libmpfr-dev
    - libgmp-dev
    - gawk
    - build-essential
    - bison
    - flex
    - texinfo
    - gperf
    - libncurses5-dev
    - libusb-1.0-0
    - libboost-dev
    # Need gcc-4.8
    - gcc-4.8
    - g++-4.8

# No Git operations will be performed. Best to fetch only the latest commit.
git:
  depth: 1

# TODO: Verify that this setting is optimal.
env:
  - JOBS=4

# Don't need email notifications for now.
notifications:
  email: false

install:
 # Download, build and install SystemC 2.3.1.
 - wget http://accellera.org/images/downloads/standards/systemc/systemc-2.3.1.tgz
 - tar -zxvf systemc-2.3.1.tgz
 - cd systemc-2.3.1 && ./configure && make && make check && make install
 - export SYSTEMC_HOME=$(pwd)
 - export SYSTEMC_INCLUDE=${SYSTEMC_HOME}/include
 - export SYSTEMC_LIBDIR=${SYSTEMC_HOME}/lib-linux64
 - cd ..
 # Download, build and install SCV 2.0.0.
 - wget http://accellera.org/images/downloads/standards/systemc/scv-2.0.0.tgz
 - tar -zxvf scv-2.0.0.tgz
 - cd scv-2.0.0 && ./configure --with-systemc=${SYSTEMC_HOME} && make && make check && make install
 - export SCV_HOME=$(pwd)
 - export SCV_INCLUDE=${SCV_HOME}/include
 - export SCV_LIBDIR=${SCV_HOME}/lib-linux64
 - cd ..
 # Export installed libraries.
 - export LD_LIBRARY_PATH=".:${SYSTEMC_LIBDIR}:${SCV_LIBDIR}"
 # Download, build and install Verilator 3.882.
 - wget https://github.com/diadatp/verilator/archive/verilator_3_882.tar.gz
 - tar -zxvf verilator_3_882.tar.gz
 - cd verilator-verilator_3_882 && autoconf && ./configure && make
 - export VERILATOR_ROOT=${PWD}
 - export PATH=${VERILATOR_ROOT}/bin:$PATH
 - verilator -V
 - cd ..

before_script:
 # Download resources required to run verification.
 - make setup
 # Build the RTL and SystemC tests.
 - make build

script:
 # Run the simulation.
 - make run

after_success:
  # Collect coverage data.
  - make coverage
  - ls -al *
  - tar -zcvf payload.tar.gz dump.vcd coverage.dat
  - curl --upload-file ./payload.tar.gz https://transfer.sh
  - make clean
